name: 'nyc_tlc'
version: '1.0.0'
config-version: 2
profile: 'nyc_tlc'
model-paths: ['models']

models:
  nyc_tlc:
    +materialized: table
    bronze:
      +schema: "{{ env_var('SNOWFLAKE_SCHEMA_RAW') }}"
      +tags: ['bronze']
    silver:
      +schema: "{{ env_var('SNOWFLAKE_SCHEMA_SILVER') }}"
      +tags: ['silver']
    gold:
      +schema: "{{ env_var('SNOWFLAKE_SCHEMA_GOLD') }}"
      +tags: ['gold']
